version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:16.17.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container all services in the project directory
          command: |
            echo "Installing dependencies..."
            sudo curl -LO https://nodejs.org/dist/v16.17.0/node-v16.17.0-linux-x64.tar.xz
            sudo tar -xvf node-v16.17.0-linux-x64.tar.xz
            sudo cp -r node-v16.17.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v16.17.0
            sudo apt install nodejs

            echo "Building images ...."

            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed buchessjo/udagram-api-feed:v1
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user buchessjo/udagram-api-user:v1
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend buchessjo/udagram-frontend:v1
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy buchessjo/udagram-reverseproxy:v1

            echo "Images built succesfully..."

            echo "Loging in to dockerhub"

            docker login -u $dockerhub_username -p $dockerhub_password

            echo "Pushing images to dockerhub..."

            docker push buchessjo/udagram-api-feed:v1
            docker push buchessjo/udagram-api-user:v1
            docker push buchessjo/udagram-frontend:v1
            docker push buchessjo/udagram-reverseproxy:v1

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]